all:\
timer \
localtime \
gmtime \
clock \
ctime \
difftime \
mktime \
strftime \


timer:timer.cpp
	g++ -o $@ $^  

localtime:localtime.cpp
	g++ -o $@ $^  

gmtime:gmtime.cpp
	g++ -o $@ $^

clock:clock.cpp
	g++ -o $@ $^

ctime:ctime.cpp
	g++ -o $@ $^

difftime:difftime.cpp
	g++ -o $@ $^

mktime::mktime.cpp
	g++ -o $@ $^

strftime::strftime.cpp
	g++ -o $@ $^

	
clean:
	rm -f *.o *~* *.txt *.out \
timer \
localtime \
gmtime \
clock \
ctime \
difftime \
mktime \
strftime \