make main=CLASS
#c
./iwant auto
./iwant break
./iwant case
./iwant char
./iwant const
./iwant continue
./iwant default
./iwant do
./iwant double
./iwant else
./iwant enum
./iwant extern
./iwant float
./iwant for
./iwant goto
./iwant if
./iwant int
./iwant long
./iwant register
./iwant return
./iwant short
./iwant signed
./iwant sizeof
./iwant static
./iwant struct
./iwant switch
./iwant typedef
./iwant union
./iwant unsigned
./iwant void
./iwant volatile
./iwant while 
#
./iwant _define	
./iwant _error	
./iwant _import	
./iwant _undef
./iwant _elif	
./iwant _if	
./iwant _include	
./iwant _using
./iwant _else	
./iwant _ifdef	
./iwant _line	
./iwant _endif
./iwant _ifndef	
./iwant _pragma		


#c++
./iwant alignas
./iwant alignof
./iwant and
./iwant and_eq
./iwant asm
./iwant atomic_cancel
./iwant atomic_commit
./iwant atomic_noexcept
./iwant auto
./iwant bitand
./iwant bitor
./iwant bool
./iwant break
./iwant case
./iwant catch
./iwant char
./iwant char16_t
./iwant char32_t
./iwant class
./iwant compl
./iwant concept
./iwant const
./iwant constexpr
./iwant const_cast
./iwant continue
./iwant decltype
./iwant default
./iwant delete
./iwant do
./iwant double
./iwant dynamic_cast
./iwant else
./iwant enum
./iwant explicit
./iwant export
./iwant extern
./iwant false
./iwant float
./iwant for
./iwant friend
./iwant goto
./iwant if
./iwant import
./iwant inline
./iwant int
./iwant long
./iwant module
./iwant mutable
./iwant namespace
./iwant new
./iwant noexcept
./iwant not
./iwant not_eq
./iwant nullptr
./iwant operator
./iwant or
./iwant or_eq
./iwant private
./iwant protected
./iwant public
./iwant register
	

./iwant reinterpret_cast
./iwant requires
./iwant return
./iwant short
./iwant signed
./iwant sizeof
./iwant static
./iwant static_assert
./iwant static_cast
./iwant struct
./iwant switch
./iwant synchronized
./iwant template
./iwant this
./iwant thread_local
./iwant throw
./iwant true
./iwant try
./iwant typedef
./iwant typeid
./iwant typename
./iwant union
./iwant unsigned
./iwant using
./iwant virtual
./iwant void
./iwant volatile
./iwant wchar_t
./iwant while
./iwant xor
./iwant xor_eq
./iwant code
make main=CLASS
