make main=CLASS

./iwant sql_ADD
./iwant sql_EXTERNAL
./iwant sql_PROCEDURE
./iwant sql_ALL
./iwant sql_FETCH
./iwant sql_PUBLIC
./iwant sql_ALTER
./iwant sql_FILE
./iwant sql_RAISERROR
./iwant sql_AND
./iwant sql_FILLFACTOR
./iwant sql_READ
./iwant sql_ANY
./iwant sql_FOR
./iwant sql_READTEXT
./iwant sql_AS
./iwant sql_FOREIGN
./iwant sql_RECONFIGURE
./iwant sql_ASC
./iwant sql_FREETEXT
./iwant sql_REFERENCES
./iwant sql_AUTHORIZATION
./iwant sql_FREETEXTTABLE
./iwant sql_REPLICATION
./iwant sql_BACKUP
./iwant sql_FROM
./iwant sql_RESTORE
./iwant sql_BEGIN
./iwant sql_FULL
./iwant sql_RESTRICT
./iwant sql_BETWEEN
./iwant sql_FUNCTION
./iwant sql_RETURN
./iwant sql_BREAK
./iwant sql_GOTO
./iwant sql_REVERT
./iwant sql_BROWSE
./iwant sql_GRANT
./iwant sql_REVOKE
./iwant sql_BULK
./iwant sql_GROUP
./iwant sql_RIGHT
./iwant sql_BY
./iwant sql_HAVING
./iwant sql_ROLLBACK
./iwant sql_CASCADE
./iwant sql_HOLDLOCK
./iwant sql_ROWCOUNT
./iwant sql_CASE
./iwant sql_IDENTITY
./iwant sql_ROWGUIDCOL
./iwant sql_CHECK
./iwant sql_IDENTITY_INSERT
./iwant sql_RULE
./iwant sql_CHECKPOINT
./iwant sql_IDENTITYCOL
./iwant sql_SAVE
./iwant sql_CLOSE
./iwant sql_IF
./iwant sql_SCHEMA
./iwant sql_CLUSTERED
./iwant sql_IN
./iwant sql_SECURITYAUDIT
./iwant sql_COALESCE
./iwant sql_INDEX
./iwant sql_SELECT
./iwant sql_COLLATE
./iwant sql_INNER
./iwant sql_SEMANTICKEYPHRASETABLE
./iwant sql_COLUMN
./iwant sql_INSERT
./iwant sql_SEMANTICSIMILARITYDETAILSTABLE
./iwant sql_COMMIT
./iwant sql_INTERSECT
./iwant sql_SEMANTICSIMILARITYTABLE
./iwant sql_COMPUTE
./iwant sql_INTO
./iwant sql_SESSION_USER
./iwant sql_CONSTRAINT
./iwant sql_IS
./iwant sql_SET
./iwant sql_CONTAINS
./iwant sql_JOIN
./iwant sql_SETUSER
./iwant sql_CONTAINSTABLE
./iwant sql_KEY
./iwant sql_SHUTDOWN
./iwant sql_CONTINUE
./iwant sql_KILL
./iwant sql_SOME
./iwant sql_CONVERT
./iwant sql_LEFT
./iwant sql_STATISTICS
./iwant sql_CREATE
./iwant sql_LIKE
./iwant sql_SYSTEM_USER
./iwant sql_CROSS
./iwant sql_LINENO
./iwant sql_TABLE
./iwant sql_CURRENT
./iwant sql_LOAD
./iwant sql_TABLESAMPLE
./iwant sql_CURRENT_DATE
./iwant sql_MERGE
./iwant sql_TEXTSIZE
./iwant sql_CURRENT_TIME
./iwant sql_NATIONAL
./iwant sql_THEN
./iwant sql_CURRENT_TIMESTAMP
./iwant sql_NOCHECK
./iwant sql_TO
./iwant sql_CURRENT_USER
./iwant sql_NONCLUSTERED
./iwant sql_TOP
./iwant sql_CURSOR
./iwant sql_NOT
./iwant sql_TRAN
./iwant sql_DATABASE
./iwant sql_NULL
./iwant sql_TRANSACTION
./iwant sql_DBCC
./iwant sql_NULLIF
./iwant sql_TRIGGER
./iwant sql_DEALLOCATE
./iwant sql_OF
./iwant sql_TRUNCATE
./iwant sql_DECLARE
./iwant sql_OFF
./iwant sql_TRY_CONVERT
./iwant sql_DEFAULT
./iwant sql_OFFSETS
./iwant sql_TSEQUAL
./iwant sql_DELETE
./iwant sql_ON
./iwant sql_UNION
./iwant sql_DENY
./iwant sql_OPEN
./iwant sql_UNIQUE
./iwant sql_DESC
./iwant sql_OPENDATASOURCE
./iwant sql_UNPIVOT
./iwant sql_DISK
./iwant sql_OPENQUERY
./iwant sql_UPDATE
./iwant sql_DISTINCT
./iwant sql_OPENROWSET
./iwant sql_UPDATETEXT
./iwant sql_DISTRIBUTED
./iwant sql_OPENXML
./iwant sql_USE
./iwant sql_DOUBLE
./iwant sql_OPTION
./iwant sql_USER
./iwant sql_DROP
./iwant sql_OR
./iwant sql_VALUES
./iwant sql_DUMP
./iwant sql_ORDER
./iwant sql_VARYING
./iwant sql_ELSE
./iwant sql_OUTER
./iwant sql_VIEW
./iwant sql_END
./iwant sql_OVER
./iwant sql_WAITFOR
./iwant sql_ERRLVL
./iwant sql_PERCENT
./iwant sql_WHEN
./iwant sql_ESCAPE
./iwant sql_PIVOT
./iwant sql_WHERE
./iwant sql_EXCEPT
./iwant sql_PLAN
./iwant sql_WHILE
./iwant sql_EXEC
./iwant sql_PRECISION
./iwant sql_WITH
./iwant sql_EXECUTE
./iwant sql_PRIMARY
./iwant sql_WITHIN_GROUP
./iwant sql_EXISTS
./iwant sql_PRINT
./iwant sql_WRITETEXT
./iwant sql_EXIT
./iwant sql_PROC

make main=CLASS