
make main=CLASS

./iwant __halt_compiler
./iwant abstract
./iwant and
./iwant array
./iwant as
./iwant break
./iwant callable
./iwant case
./iwant catch
./iwant class
./iwant clone
./iwant const
./iwant continue
./iwant declare
./iwant default
./iwant die
./iwant do
./iwant echo
./iwant else
./iwant elseif
./iwant empty
./iwant enddeclare
./iwant endfor
./iwant endforeach
./iwant endif
./iwant endswitch
./iwant endwhile
./iwant eval
./iwant exit
./iwant extends
./iwant final
./iwant finally
./iwant for
./iwant foreach
./iwant function
./iwant global
./iwant goto
./iwant if
./iwant implements
./iwant include
./iwant include_once
./iwant instanceof
./iwant insteadof
./iwant interface
./iwant isset
./iwant list
./iwant namespace
./iwant new
./iwant or
./iwant print
./iwant private
./iwant protected
./iwant public
./iwant require
./iwant require_once
./iwant return
./iwant static
./iwant switch
./iwant throw
./iwant trait
./iwant try
./iwant unset
./iwant use
./iwant var
./iwant while
./iwant xor 	
./iwant yield 			

./iwant __CLASS__
./iwant __DIR__
./iwant __FILE__
./iwant __FUNCTION__
./iwant __LINE__
./iwant __METHOD__
./iwant __NAMESPACE__
./iwant __TRAIT__ 

make main=CLASS