make main=CLASS

./iwant abstract
./iwant continue
./iwant for
./iwant new
./iwant switch
./iwant assert
./iwant default
./iwant goto
./iwant package
./iwant synchronized
./iwant boolean
./iwant do
./iwant if
./iwant private
./iwant this
./iwant break
./iwant double
./iwant implements
./iwant protected
./iwant throw
./iwant byte
./iwant else
./iwant import
./iwant public
./iwant throws
./iwant case
./iwant enum
./iwant instanceof
./iwant return
./iwant transient
./iwant catch
./iwant extends
./iwant int
./iwant short
./iwant try
./iwant char
./iwant final
./iwant interface
./iwant static
./iwant void
./iwant class
./iwant finally
./iwant long
./iwant strictfp
./iwant volatile
./iwant const
./iwant float
./iwant native
./iwant super
./iwant while

make main=CLASS