make main=CLASS
./iwant 
./iwant __abstract
./iwant __alignof
./iwant Operator
./iwant __asm
./iwant __assume
./iwant __based
./iwant __box
./iwant __cdecl
./iwant __declspec
./iwant __delegate
./iwant __event
./iwant __except
./iwant __fastcall
./iwant __finally
./iwant __forceinline
./iwant __gc
./iwant __hook
./iwant __identifier
./iwant __if_exists
./iwant __if_not_exists
./iwant __inline
./iwant __int16
./iwant __int32
./iwant __int64
./iwant __int8
./iwant __interface
./iwant __leave
./iwant __m128
./iwant __m128d
./iwant __m128i
./iwant __m64
./iwant __multiple_inheritance
./iwant __nogc
./iwant __noop
./iwant __pin 
./iwant __property
./iwant __raise
./iwant __sealed
./iwant __single_inheritance
./iwant __stdcall
./iwant __super
./iwant __thiscall
./iwant __try__except
./iwant __try__finally
./iwant __try_cast
./iwant __unaligned
./iwant __unhook
./iwant __uuidof
./iwant __value
./iwant __virtual_inheritance
./iwant __w64
./iwant __wchar_t
./iwant wchar_t
./iwant abstract
./iwant array
./iwant auto
./iwant bool
./iwant break
./iwant case
./iwant catch
./iwant char
./iwant class
./iwant const
./iwant const_cast
./iwant continue
./iwant decltype
./iwant default
./iwant delegate
./iwant delete
./iwant deprecated
./iwant dllexport
./iwant dllimport
./iwant do
./iwant double
./iwant dynamic_cast
./iwant else
./iwant enum
./iwant enum_class
./iwant enum_struct
./iwant event
./iwant explicit
./iwant extern
./iwant false
./iwant finally
./iwant float
./iwant for
./iwant for_each_in
./iwant friend
./iwant friend_as
./iwant gcnew
./iwant generic
./iwant goto
./iwant if
./iwant initonly
./iwant inline
./iwant int
./iwant interface_class
./iwant interface_struct
./iwant interior_ptr
./iwant literal
./iwant long
./iwant mutable
./iwant naked 
./iwant namespace
./iwant new
./iwant new_noinline 
./iwant noreturn
./iwant nothrow 
./iwant novtable
./iwant nullptr
./iwant operator
./iwant private
./iwant property
./iwant property
./iwant protected
./iwant public
./iwant ref_class
./iwant ref_struct
./iwant register
./iwant reinterpret_cast
./iwant return
./iwant safecast
./iwant sealed
./iwant selectany
./iwant short
./iwant signed
./iwant sizeof
./iwant static
./iwant static_assert
./iwant static_cast
./iwant struct
./iwant switch
./iwant template
./iwant this
./iwant thread
./iwant throw
./iwant true
./iwant try
./iwant typedef
./iwant typeid
./iwant typeid
./iwant typename
./iwant union
./iwant unsigned
./iwant using_declaration
./iwant using_directive
./iwant uuid
./iwant value_class
./iwant value_struct
./iwant virtual
./iwant void
./iwant volatile
./iwant while

make main=CLASS