make main=CLASS
./iwant display
./iwant get
./iwant makefile
./iwant search
./iwant schedule
./iwant ftp
./iwant smtp
./iwant step
./iwant test
./iwant func
./iwant company
./iwant register
make main=CLASS