all:\
acos \
acosh \
asin \
asinh \
atan \
atan2 \
atanh \
cbrt \
ceil \
copysign \
cos \
cosh \
erf \
erfc \
exp \
exp2 \
expm1 \
fabs \
fdim \
floor \
fma \
fmax \
fmin \
fmod \
fpclassify \
frexp \
hypot \
ilogb \
isfinite \
isgreater \
isgreaterequal \
isinf \
isless \
islessequal \
islessgreater \
isnan \
isnormal \
isunordered \
ldexp \
lgamma \
llrint \
llround \
log \
log10 \
log1p \
log2 \
logb \
lrint \
lround \
modf \
nearbyint \
nextafter \
nexttoward \
pow \
remainder \
remquo \
rfct \
rint \
scalbln \
scalbn \
signbit \
sin \
sinh \
sqrt \
std-abs \
tan \
tanh \
tgamma \

acos:acos.cpp  
		g++ -o $@ $^  
acosh:acosh.cpp  
		g++ -o $@ $^  
asin:asin.cpp  
		g++ -o $@ $^  
asinh:asinh.cpp  
		g++ -o $@ $^  
atan:atan.cpp  
		g++ -o $@ $^  
atan2:atan2.cpp  
		g++ -o $@ $^  
atanh:atanh.cpp  
		g++ -o $@ $^  
cbrt:cbrt.cpp  
		g++ -o $@ $^  
ceil:ceil.cpp  
		g++ -o $@ $^  
copysign:copysign.cpp  
		g++ -o $@ $^  
cos:cos.cpp  
		g++ -o $@ $^  
cosh:cosh.cpp  
		g++ -o $@ $^  
erf:erf.cpp  
		g++ -o $@ $^  
erfc:erfc.cpp  
		g++ -o $@ $^  
exp:exp.cpp  
		g++ -o $@ $^  
exp2:exp2.cpp  
		g++ -o $@ $^  
expm1:expm1.cpp  
		g++ -o $@ $^  
fabs:fabs.cpp  
		g++ -o $@ $^  
fdim:fdim.cpp  
		g++ -o $@ $^  
floor:floor.cpp  
		g++ -o $@ $^  
fma:fma.cpp  
		g++ -o $@ $^  
fmax:fmax.cpp  
		g++ -o $@ $^  
fmin:fmin.cpp  
		g++ -o $@ $^  
fmod:fmod.cpp  
		g++ -o $@ $^  
fpclassify:fpclassify.cpp  
		g++ -o $@ $^  
frexp:frexp.cpp  
		g++ -o $@ $^  
hypot:hypot.cpp  
		g++ -o $@ $^  
ilogb:ilogb.cpp  
		g++ -o $@ $^  
isfinite:isfinite.cpp  
		g++ -o $@ $^  
isgreater:isgreater.cpp  
		g++ -o $@ $^  
isgreaterequal:isgreaterequal.cpp  
		g++ -o $@ $^  
isinf:isinf.cpp  
		g++ -o $@ $^  
isless:isless.cpp  
		g++ -o $@ $^  
islessequal:islessequal.cpp  
		g++ -o $@ $^  
islessgreater:islessgreater.cpp  
		g++ -o $@ $^  
isnan:isnan.cpp  
		g++ -o $@ $^  
isnormal:isnormal.cpp  
		g++ -o $@ $^  
isunordered:isunordered.cpp  
		g++ -o $@ $^  
ldexp:ldexp.cpp  
		g++ -o $@ $^  
lgamma:lgamma.cpp  
		g++ -o $@ $^  
llrint:llrint.cpp  
		g++ -o $@ $^  
llround:llround.cpp  
		g++ -o $@ $^  
log:log.cpp  
		g++ -o $@ $^  
log10:log10.cpp  
		g++ -o $@ $^  
log1p:log1p.cpp  
		g++ -o $@ $^  
log2:log2.cpp  
		g++ -o $@ $^  
logb:logb.cpp  
		g++ -o $@ $^  
lrint:lrint.cpp  
		g++ -o $@ $^  
lround:lround.cpp  
		g++ -o $@ $^  
modf:modf.cpp  
		g++ -o $@ $^  
nearbyint:nearbyint.cpp  
		g++ -o $@ $^  
nextafter:nextafter.cpp  
		g++ -o $@ $^  
nexttoward:nexttoward.cpp  
		g++ -o $@ $^  
pow:pow.cpp  
		g++ -o $@ $^  
remainder:remainder.cpp  
		g++ -o $@ $^  
remquo:remquo.cpp  
		g++ -o $@ $^  
rfct:rfct.cpp  
		g++ -o $@ $^  
rint:rint.cpp  
		g++ -o $@ $^  
scalbln:scalbln.cpp  
		g++ -o $@ $^  
scalbn:scalbn.cpp  
		g++ -o $@ $^  
signbit:signbit.cpp  
		g++ -o $@ $^  
sin:sin.cpp  
		g++ -o $@ $^  
sinh:sinh.cpp  
		g++ -o $@ $^  
sqrt:sqrt.cpp  
		g++ -o $@ $^  
std-abs:std-abs.cpp  
		g++ -o $@ $^  
tan:tan.cpp  
		g++ -o $@ $^  
tanh:tanh.cpp  
		g++ -o $@ $^  
tgamma:tgamma.cpp  
		g++ -o $@ $^  
clean:
	rm -f fstream *.o *~* *.txt *.out \
acos \
acosh \
asin \
asinh \
atan \
atan2 \
atanh \
cbrt \
ceil \
copysign \
cos \
cosh \
erf \
erfc \
exp \
exp2 \
expm1 \
fabs \
fdim \
floor \
fma \
fmax \
fmin \
fmod \
fpclassify \
frexp \
hypot \
ilogb \
isfinite \
isgreater \
isgreaterequal \
isinf \
isless \
islessequal \
islessgreater \
isnan \
isnormal \
isunordered \
ldexp \
lgamma \
llrint \
llround \
log \
log10 \
log1p \
log2 \
logb \
lrint \
lround \
modf \
nearbyint \
nextafter \
nexttoward \
pow \
remainder \
remquo \
rfct \
rint \
scalbln \
scalbn \
signbit \
sin \
sinh \
sqrt \
std-abs \
tan \
tanh \
tgamma \

