all:\
acos \
asin \
atan \
cos \
log10 \
sin \
tan \

acos:acos.cpp  
		g++ -o $@ $^  
asin:asin.cpp  
		g++ -o $@ $^  
atan:atan.cpp  
		g++ -o $@ $^  
cos:cos.cpp  
		g++ -o $@ $^  
log10:log10.cpp  
		g++ -o $@ $^  
sin:sin.cpp  
		g++ -o $@ $^  
tan:tan.cpp  
		g++ -o $@ $^  
