#ifndef CTYPE_ALL_H_INCLUDE 
#define CTYPE_ALL_H_INCLUDE 

#include "ctype.h" 
#include "isalnum.h" 
#include "isalpha.h" 
#include "isblank.h" 
#include "iscntrl.h" 
#include "isdigit.h" 
#include "isgraph.h" 
#include "islower.h" 
#include "isprint.h" 
#include "ispunct.h" 
#include "isspace.h" 
#include "isupper.h" 
#include "iswalnum.h" 
#include "iswalpha.h" 
#include "iswblank.h" 
#include "iswcntrl.h" 
#include "iswctype.h" 
#include "iswdigit.h" 
#include "iswgraph.h" 
#include "iswlower.h" 
#include "iswprint.h" 
#include "iswpunct.h" 
#include "iswspace.h" 
#include "iswupper.h" 
#include "iswxdigit.h" 
#include "isxdigit.h" 
#include "tolower.h" 
#include "toupper.h" 
#include "towctrans.h" 
#include "towlower.h" 
#include "towupper.h" 
#include "wctrans.h" 
#include "wctype.h" 
 
#endif 
