#ifndef ALL_H_INCLUDE 
#define ALL_H_INCLUDE 

#include "class.h" 
#include "cout.h" 
#include "echo.h" 
#include "esc.h" 
#include "exec.h" 
#include "exit.h" 
#include "home.h" 
#include "iwant.h" 
#include "main.h" 
#include "math.h" 
#include "myMemory.h" 
#include "net.h" 
#include "new.h" 
#include "object.h" 
#include "os.h" 
#include "run.h" 
#include "socket.h" 
#include "syntax.h" 
#include "syntax_def.h" 
#include "sys.h" 
#include "tag.h" 
#include "task.h" 
#include "temp.h" 
#include "temp_def.h" 
#include "url.h" 
 
#endif 
